export enum ExpressionType {
    AGE = 'ALDER',
    INDICATION = 'INDIKATION',
    DOCTOR_SPECIALITY = 'LÆGESPECIALE',
    DEPARTMENT_SPECIALITY = 'AFDELINGSSPECIALE',
    EXISTING_DRUG_MEDICATION = 'EKSISTERENDE_LÆGEMIDDEL'
}