services:
  
  init:
    image: local/init
    user: "101:101"
    environment:
    - REACT_APP_API_BASEURL=http://localhost:3030/api
    - REACT_APP_NODE_ENV=dev
    - REACT_APP_KEYCLOAK_URL=http://localhost:49152/auth
    - REACT_APP_KEYCLOAK_REALM=Test
    - REACT_APP_KEYCLOAK_CLIENTID=klausuleret-tilskud-ui-ui
    build:
      context: ../
      dockerfile: ./Dockerfile
    volumes:
      - init-dockerentrypoint:/temp/docker-entrypoint.d
      - nginx:/temp/etc/nginx
      - run:/temp/var/run
      - cache-nginx:/temp/var/cache/nginx
  frontend:
    image: nginxinc/nginx-unprivileged:alpine3.17
    restart: always
    volumes:
      - init-dockerentrypoint:/docker-entrypoint.d
      - nginx:/etc/nginx
      - run:/var/run
      - cache-nginx:/var/cache/nginx
    ports:
      - "3000:80"
    depends_on:
      - init
      
volumes:
  init-dockerentrypoint:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  nginx:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  cache-nginx:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  run:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs