services:
  itukt-ui:
    environment:
    - ITUKT_AUTH_GATEWAY_URL=https://klaus-gateway-without-oiosaml.t0.hosting.kitkube.dk
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - "4200:8080"